version: "3.6"

services:
  static-mlflow-dev-image:
    image: static-mlflow-dev-image
    volumes:
    - .:/repo-root
    - ./mlflow/server/js:/front-dev
    ports:
    - "5000:5000"
    - "3001:3001"
    command: |
      tail -f /dev/null
    hostname: static-mlflow-dev-image
