name: "Reusable workflow to build and publish webui py package"

on:
  workflow_call:

defaults:
  run:
    shell: bash
    working-directory: ./mlflow/server/js
    # Note: ${{ github.workspace }} not supported with working-directory

jobs:
  main-step:
    name: Build and publish Python package with compiled static web assets
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: false

      - name: "Compile static UI: build Docker image"
        run: |
          make docker-build-image-for-build-static-ui

      - name: "Compile static UI: Compile front end code"
        run: |
          make docker-build-static-ui

      - name: "webui-py-package: build Docker image"
        run: |
          make webui-py-package/docker/build-image

      - name: "webui-py-package: build Python wheel with UI static assets"
        run: |
          make webui-py-package/build-wheel[in-docker]

      - name: "Store output wheel-file as Github build artefact"
        uses: actions/upload-artifact@v3
        with:
          name: webui-py-package-wheel-file
          path: ${{ github.workspace }}/mlflow/server/js/webui-py-package/dist/
          if-no-files-found: error
          retention-days: 7
