name: "Reusable workflow to build and publish webui py package"

on:
  workflow_call:

defaults:
  run:
    shell: bash
    working-directory: ${{ github.workspace }}/mlflow/server/js

jobs:
  foo:
    name: Build and publish Python package with compiled static web assets
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: false

      - name: "Compile static UI: build Docker image"
        run: |
          make docker-build-image-for-build-static-ui

      - name: "Compile static UI: Compile front end code"
        run: |
          make docker-build-static-ui

      - name: "webui-py-package: build Docker image"
        run: |
          make webui-py-package/docker/build-image

      - name: "webui-py-package: build Python wheel with UI static assets"
        run: |
          make webui-py-package/build-wheel-file[in-docker]
