name: "ci/cd: main release to PyPI"

on:
  push:
    branches:
      - static_mlflow
    paths:
      - mlflow/server/js/webui-py-package/PYTHON_PACKAGE_VERSION

jobs:
  ci-run-tests:
    permissions:
      contents: none
    uses: ./.github/workflows/_ci-build-and-publish-webui-py-package.yml
    with:
      python-package-release-target: main-release

  cd-publish-package:
    needs: ci-run-tests
    permissions:
      contents: none
    uses: ./.github/workflows/_cd-publish-main-release.yml
    secrets:
      PYPI_SECRET_API_TOKEN: ${{ secrets.GH_PYPI_SECRET_API_TOKEN }}

  cd-tag-release-commit:
    needs: cd-publish-package
    runs-on: ubuntu-20.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: true

      - name: Determining version for this release
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          echo "PYTHON_PACKAGE_VERSION=$( \
            cat ./mlflow/server/js/webui-py-package/PYTHON_PACKAGE_VERSION | \
                head -n 1 - \
          )" >> $GITHUB_ENV
          echo "PYTHON_PACKAGE_VERSION = ${PYTHON_PACKAGE_VERSION}"

      - name: Tag git-commit with version for this release
        shell: bash
        run: |
          git tag "static-v${PYTHON_PACKAGE_VERSION}" main
          git push origin "static-v${PYTHON_PACKAGE_VERSION}"
